import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "get-started",
      "children": [
        {
          "slug": "introduction"
        },
        {
          "slug": "installation"
        },
        {
          "slug": "usage"
        }
      ]
    },
    {
      "slug": "concepts",
      "children": [
        {
          "slug": "agent"
        },
        {
          "slug": "tools"
        },
        {
          "slug": "providers"
        },
        {
          "slug": "api"
        },
        {
          "slug": "client"
        },
        {
          "slug": "events"
        },
        {
          "slug": "persistence"
        },
        {
          "slug": "plugins"
        },
        {
          "slug": "typescript"
        },
        {
          "slug": "cli"
        },
        {
          "slug": "structured-output"
        },
        {
          "slug": "hil"
        },
        {
          "slug": "mcp"
        },
        {
          "slug": "errors"
        }
      ]
    },
    {
      "slug": "plugins",
      "children": [
        {
          "slug": "auth"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
